"""phase 0: 16 regulation tables

Revision ID: 03250b77ed3b
Revises: 
Create Date: 2026-09-11 21:34:18.306243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03250b77ed3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_activity',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['business_activity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('entity_type',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['entity_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_type',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('regulator',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('document',
    sa.Column('regulator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_version',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_uri', sa.String(length=1000), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_relationship',
    sa.Column('from_document_id', sa.UUID(), nullable=False),
    sa.Column('to_document_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['to_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_page',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('image_uri', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_run',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.ForeignKeyConstraint(['parent_section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_requirement',
    sa.Column('stable_key', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('clause_type', sa.String(length=30), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('confidence_extraction', sa.Float(), nullable=True),
    sa.Column('confidence_source_match', sa.Float(), nullable=True),
    sa.Column('confidence_classification', sa.Float(), nullable=True),
    sa.Column('confidence_applicability', sa.Float(), nullable=True),
    sa.Column('confidence_interpretation', sa.Float(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['regulatory_requirement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_key', 'revision_number', name='uq_requirement_stable_revision')
    )
    op.create_table('applicability_rule',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=10), nullable=False),
    sa.Column('entity_type_id', sa.UUID(), nullable=True),
    sa.Column('product_type_id', sa.UUID(), nullable=True),
    sa.Column('business_activity_id', sa.UUID(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_activity_id'], ['business_activity.id'], ),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_type.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['regulatory_requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligation',
    sa.Column('stable_key', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('deadline_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('confidence_extraction', sa.Float(), nullable=True),
    sa.Column('confidence_source_match', sa.Float(), nullable=True),
    sa.Column('confidence_classification', sa.Float(), nullable=True),
    sa.Column('confidence_applicability', sa.Float(), nullable=True),
    sa.Column('confidence_interpretation', sa.Float(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['regulatory_requirement.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['obligation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_key', 'revision_number', name='uq_obligation_stable_revision')
    )
    op.create_table('regulatory_change',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('old_requirement_id', sa.UUID(), nullable=True),
    sa.Column('new_requirement_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.ForeignKeyConstraint(['new_requirement_id'], ['regulatory_requirement.id'], ),
    sa.ForeignKeyConstraint(['old_requirement_id'], ['regulatory_requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_citation',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('document_page_id', sa.UUID(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_page.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['regulatory_requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_identifier', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(num_nonnulls(requirement_id, obligation_id) = 1)', name='ck_review_exactly_one_target'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligation.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['regulatory_requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('source_citation')
    op.drop_table('regulatory_change')
    op.drop_table('obligation')
    op.drop_table('applicability_rule')
    op.drop_table('regulatory_requirement')
    op.drop_table('section')
    op.drop_table('extraction_run')
    op.drop_table('document_page')
    op.drop_table('regulatory_relationship')
    op.drop_table('document_version')
    op.drop_table('document')
    op.drop_table('regulator')
    op.drop_table('product_type')
    op.drop_table('entity_type')
    op.drop_table('business_activity')
    # ### end Alembic commands ###
