"""extend applicability_rule and review for applicability review workflow

Revision ID: 1daf7ebe7feb
Revises: 9676b8e744d5
Create Date: 2026-09-16 22:18:37.798166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1daf7ebe7feb'
down_revision: Union[str, Sequence[str], None] = '9676b8e744d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicability_rule', sa.Column('entity_type_text', sa.String(length=255), nullable=True))
    op.add_column('applicability_rule', sa.Column('product_type_text', sa.String(length=255), nullable=True))
    op.add_column('applicability_rule', sa.Column('business_activity_text', sa.String(length=255), nullable=True))
    op.add_column('applicability_rule', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('applicability_rule', sa.Column('confidence_extraction', sa.Float(), nullable=True))
    op.add_column('applicability_rule', sa.Column('extraction_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'applicability_rule', 'extraction_run', ['extraction_run_id'], ['id'])
    op.add_column('review', sa.Column('applicability_rule_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'review', 'applicability_rule', ['applicability_rule_id'], ['id'])
    # ### end Alembic commands ###

    # not auto-detected by autogenerate (check constraint bodies aren't
    # tracked) -- added by hand, same as the last two migrations
    op.create_check_constraint(
        'ck_applicability_entity_not_both',
        'applicability_rule',
        'NOT (entity_type_id IS NOT NULL AND entity_type_text IS NOT NULL)',
    )
    op.create_check_constraint(
        'ck_applicability_product_not_both',
        'applicability_rule',
        'NOT (product_type_id IS NOT NULL AND product_type_text IS NOT NULL)',
    )
    op.create_check_constraint(
        'ck_applicability_activity_not_both',
        'applicability_rule',
        'NOT (business_activity_id IS NOT NULL AND business_activity_text IS NOT NULL)',
    )
    op.drop_constraint('ck_review_exactly_one_target', 'review', type_='check')
    op.create_check_constraint(
        'ck_review_exactly_one_target',
        'review',
        '(num_nonnulls(requirement_id, obligation_id, relationship_id, applicability_rule_id) = 1)',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_review_exactly_one_target', 'review', type_='check')
    op.create_check_constraint(
        'ck_review_exactly_one_target',
        'review',
        '(num_nonnulls(requirement_id, obligation_id, relationship_id) = 1)',
    )
    op.drop_constraint('ck_applicability_activity_not_both', 'applicability_rule', type_='check')
    op.drop_constraint('ck_applicability_product_not_both', 'applicability_rule', type_='check')
    op.drop_constraint('ck_applicability_entity_not_both', 'applicability_rule', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'applicability_rule_id')
    op.drop_constraint(None, 'applicability_rule', type_='foreignkey')
    op.drop_column('applicability_rule', 'extraction_run_id')
    op.drop_column('applicability_rule', 'confidence_extraction')
    op.drop_column('applicability_rule', 'status')
    op.drop_column('applicability_rule', 'business_activity_text')
    op.drop_column('applicability_rule', 'product_type_text')
    op.drop_column('applicability_rule', 'entity_type_text')
    # ### end Alembic commands ###
