"""remove unused confidence_applicability column

Dropped because it was never populated: confirmed 0/387 regulatory_requirement
rows and 0/337 obligation rows had a non-null value, and no extraction code
anywhere writes to it. ApplicabilityRule.confidence_extraction (its own
table, added in an earlier Phase 2 migration) already covers that
dimension -- one score per scoping rule, not one aggregate column on the
parent requirement/obligation.

The regulatory_requirement immutability trigger (migration
4dab71b57fe1) references this column by name in its content-change check,
so the trigger function must be replaced (dropping that one clause)
BEFORE the column can be dropped -- autogenerate doesn't know about
trigger bodies, only column/constraint DDL, so that part is hand-written.

Revision ID: 2d192ed187eb
Revises: 4da1e6f61531
Create Date: 2026-10-06 13:53:49.411691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d192ed187eb'
down_revision: Union[str, Sequence[str], None] = '4da1e6f61531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE OR REPLACE FUNCTION regulatory_requirement_block_content_update()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.id IS DISTINCT FROM OLD.id
               OR NEW.stable_key IS DISTINCT FROM OLD.stable_key
               OR NEW.revision_number IS DISTINCT FROM OLD.revision_number
               OR NEW.document_version_id IS DISTINCT FROM OLD.document_version_id
               OR NEW.section_id IS DISTINCT FROM OLD.section_id
               OR NEW.clause_type IS DISTINCT FROM OLD.clause_type
               OR NEW.requirement_text IS DISTINCT FROM OLD.requirement_text
               OR NEW.effective_date IS DISTINCT FROM OLD.effective_date
               OR NEW.confidence_extraction IS DISTINCT FROM OLD.confidence_extraction
               OR NEW.confidence_source_match IS DISTINCT FROM OLD.confidence_source_match
               OR NEW.confidence_classification IS DISTINCT FROM OLD.confidence_classification
               OR NEW.confidence_interpretation IS DISTINCT FROM OLD.confidence_interpretation
               OR NEW.extraction_run_id IS DISTINCT FROM OLD.extraction_run_id
               OR NEW.created_at IS DISTINCT FROM OLD.created_at
            THEN
                RAISE EXCEPTION
                    'regulatory_requirement rows are immutable: only status and superseded_by_id may change (id=%)',
                    OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligation', 'confidence_applicability')
    op.drop_column('regulatory_requirement', 'confidence_applicability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_requirement', sa.Column('confidence_applicability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('obligation', sa.Column('confidence_applicability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION regulatory_requirement_block_content_update()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.id IS DISTINCT FROM OLD.id
               OR NEW.stable_key IS DISTINCT FROM OLD.stable_key
               OR NEW.revision_number IS DISTINCT FROM OLD.revision_number
               OR NEW.document_version_id IS DISTINCT FROM OLD.document_version_id
               OR NEW.section_id IS DISTINCT FROM OLD.section_id
               OR NEW.clause_type IS DISTINCT FROM OLD.clause_type
               OR NEW.requirement_text IS DISTINCT FROM OLD.requirement_text
               OR NEW.effective_date IS DISTINCT FROM OLD.effective_date
               OR NEW.confidence_extraction IS DISTINCT FROM OLD.confidence_extraction
               OR NEW.confidence_source_match IS DISTINCT FROM OLD.confidence_source_match
               OR NEW.confidence_classification IS DISTINCT FROM OLD.confidence_classification
               OR NEW.confidence_applicability IS DISTINCT FROM OLD.confidence_applicability
               OR NEW.confidence_interpretation IS DISTINCT FROM OLD.confidence_interpretation
               OR NEW.extraction_run_id IS DISTINCT FROM OLD.extraction_run_id
               OR NEW.created_at IS DISTINCT FROM OLD.created_at
            THEN
                RAISE EXCEPTION
                    'regulatory_requirement rows are immutable: only status and superseded_by_id may change (id=%)',
                    OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
