"""add confidence_classification and confidence_source_match to relationship and applicability_rule

Revision ID: 4da1e6f61531
Revises: 1daf7ebe7feb
Create Date: 2026-10-06 13:45:00.858956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da1e6f61531'
down_revision: Union[str, Sequence[str], None] = '1daf7ebe7feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicability_rule', sa.Column('confidence_classification', sa.Float(), nullable=True))
    op.add_column('applicability_rule', sa.Column('confidence_source_match', sa.Float(), nullable=True))
    op.add_column('regulatory_relationship', sa.Column('confidence_classification', sa.Float(), nullable=True))
    op.add_column('regulatory_relationship', sa.Column('confidence_source_match', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatory_relationship', 'confidence_source_match')
    op.drop_column('regulatory_relationship', 'confidence_classification')
    op.drop_column('applicability_rule', 'confidence_source_match')
    op.drop_column('applicability_rule', 'confidence_classification')
    # ### end Alembic commands ###
