"""extend regulatory_relationship for external refs and review workflow

Revision ID: 6b546348f9b3
Revises: e1d1e041d0ea
Create Date: 2026-09-16 21:53:57.642560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b546348f9b3'
down_revision: Union[str, Sequence[str], None] = 'e1d1e041d0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_relationship', sa.Column('external_reference_text', sa.Text(), nullable=True))
    op.add_column('regulatory_relationship', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('regulatory_relationship', sa.Column('confidence_extraction', sa.Float(), nullable=True))
    op.add_column('regulatory_relationship', sa.Column('source_requirement_id', sa.UUID(), nullable=True))
    op.add_column('regulatory_relationship', sa.Column('extraction_run_id', sa.UUID(), nullable=True))
    op.alter_column('regulatory_relationship', 'to_document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'regulatory_relationship', 'regulatory_requirement', ['source_requirement_id'], ['id'])
    op.create_foreign_key(None, 'regulatory_relationship', 'extraction_run', ['extraction_run_id'], ['id'])
    # not auto-detected by autogenerate -- added by hand
    op.create_check_constraint(
        'ck_relationship_exactly_one_target',
        'regulatory_relationship',
        '(num_nonnulls(to_document_id, external_reference_text) = 1)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_relationship_exactly_one_target', 'regulatory_relationship', type_='check')
    op.drop_constraint(None, 'regulatory_relationship', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_relationship', type_='foreignkey')
    op.alter_column('regulatory_relationship', 'to_document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('regulatory_relationship', 'extraction_run_id')
    op.drop_column('regulatory_relationship', 'source_requirement_id')
    op.drop_column('regulatory_relationship', 'confidence_extraction')
    op.drop_column('regulatory_relationship', 'status')
    op.drop_column('regulatory_relationship', 'external_reference_text')
    # ### end Alembic commands ###
