"""review supports relationship_id target

Revision ID: 9676b8e744d5
Revises: 6b546348f9b3
Create Date: 2026-09-16 22:11:44.550675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9676b8e744d5'
down_revision: Union[str, Sequence[str], None] = '6b546348f9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('relationship_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'review', 'regulatory_relationship', ['relationship_id'], ['id'])
    # ### end Alembic commands ###
    # not auto-detected by autogenerate (same as before -- it doesn't
    # track CHECK constraint body changes) -- added by hand
    op.drop_constraint('ck_review_exactly_one_target', 'review', type_='check')
    op.create_check_constraint(
        'ck_review_exactly_one_target',
        'review',
        '(num_nonnulls(requirement_id, obligation_id, relationship_id) = 1)',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_review_exactly_one_target', 'review', type_='check')
    op.create_check_constraint(
        'ck_review_exactly_one_target',
        'review',
        '(num_nonnulls(requirement_id, obligation_id) = 1)',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'relationship_id')
    # ### end Alembic commands ###
