"""add high-risk flag to regulatory_requirement

Revision ID: e1d1e041d0ea
Revises: 4dab71b57fe1
Create Date: 2026-09-11 22:44:36.212247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d1e041d0ea'
down_revision: Union[str, Sequence[str], None] = '4dab71b57fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_requirement', sa.Column('contains_high_risk_language', sa.Boolean(), nullable=False))
    op.add_column('regulatory_requirement', sa.Column('high_risk_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatory_requirement', 'high_risk_notes')
    op.drop_column('regulatory_requirement', 'contains_high_risk_language')
    # ### end Alembic commands ###
